name: oshiire-jiho-ch
services:
  oshiire-jiho-ch:
    build:
      context: .
      dockerfile: ./app/build/Dockerfile
    container_name: oshiire-jiho-ch
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./app/config
        target: /app/config
        readonly: false
        bind:
          create_host_path: true
      - type: bind
        source: ./app/data
        target: /app/data
        readonly: false
        bind:
          create_host_path: true
      - type: bind
        source: ./app/bin
        target: /app/bin
        readonly: true
        bind:
          create_host_path: true
      - type: bind
        source: ./app/log
        target: /app/log
        readonly: false
        bind:
          create_host_path: true
